export const LOAD_HOTELS_SUCCESS = "LOAD_HOTELS_SUCCESS";
export const SAVE_HOTEL_SUCCESS = "SAVE_HOTEL_SUCCESS";
export const EDIT_HOTEL_SUCCESS = "EDIT_HOTEL_SUCCESS";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
